### ISSUE TITLE
More complete in-code documentation

### ISSUE THREAD

**Issue by RespiteSage** [geocrystal/geo_json#3]
Hey, there. I just discovered your GeoCrystal shards on accident, but I have [my own shard that I just published](https://github.com/kinxer/crgeojson), and I have to say that this is much more complete. The only thing I see missing is class- and method-level documentation. I'm happy to work on this myself (probably re-using a lot of the documentation from my shard), and I'm also interested in helping with any future GeoCrystal work you're thinking of.

**Comment by mamantoha** [comment]
Hi @kinxer . I checked your shard. It's doing almost the same job.
If you are interested in helping I can add you to this organization.

**Comment by RespiteSage** [comment]
Sorry I've taken so long to get back to you. I am definitely interested in helping. I can't necessarily promise weekly participation, but I'll do what I can.
